node{
   
   stage('--SCM Checkout--'){
     git'https://github.com/sharanukoti/DemoRepo.git'
  }
  stage('--Build--'){
    bat  "mvn clean package -f demo-war"
  }
  stage('--Deploy--'){
    bat "mvn wildfly:deploy tagret/*.war -DappDplySrvr.host=10.235.194.141 -DappDplySrvr.port=5000"
  }
}
