node{
   agent any
   stage('--SCM Checkout--'){
    git'https://github.com/sharanukoti/DemoRepo.git'
  }
  stage('--Build--'){
    
    bat  "mvn clean package -f demo-war"
  }
  stage('--deploy--'){
    bat "mvn tomcat7:deploy tagret/*.war -DappDplySrvr.host=10.235.194.141 -DappDplySrvr.port=1000"
  }
}
