node{
  def mvnHome
  stage('SCM Checkout'){
    git'https://github.com/sharanukoti/DemoRepo.git'
    mvnHome = tool 'mavenHome'
  }
  stage('Build'){
    sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
  }
  
}
